spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
